export const menuData = [
  // Burgers
  {
    id: "burger-1",
    name: "Classic Crunch Burger",
    description: "Juicy beef patty with lettuce, tomato, cheese, and our signature sauce",
    price: 2500,
    image: "/classic-beef-burger-with-cheese.jpg",
    category: "Burgers",
  },
  {
    id: "burger-2",
    name: "Double Trouble Burger",
    description: "Two beef patties, double cheese, bacon, and special sauce",
    price: 3500,
    image: "/double-beef-burger-with-bacon.jpg",
    category: "Burgers",
  },
  {
    id: "burger-3",
    name: "Spicy Chicken Burger",
    description: "Crispy chicken breast with spicy mayo and jalapeños",
    price: 2800,
    image: "/spicy-chicken-burger.png",
    category: "Burgers",
  },
  {
    id: "burger-4",
    name: "Veggie Delight Burger",
    description: "Plant-based patty with fresh vegetables and avocado",
    price: 2700,
    image: "/vegetarian-avocado-burger.png",
    category: "Burgers",
  },

  // Rice
  {
    id: "rice-1",
    name: "Jollof Rice Special",
    description: "Nigerian-style jollof rice with chicken and plantain",
    price: 2000,
    image: "/jollof-rice-chicken.png",
    category: "Rice",
  },
  {
    id: "rice-2",
    name: "Fried Rice Combo",
    description: "Delicious fried rice with mixed vegetables and protein",
    price: 2200,
    image: "/fried-rice-with-vegetables.jpg",
    category: "Rice",
  },
  {
    id: "rice-3",
    name: "Coconut Rice Bowl",
    description: "Aromatic coconut rice with grilled chicken",
    price: 2400,
    image: "/coconut-rice-bowl.jpg",
    category: "Rice",
  },

  // Chicken
  {
    id: "chicken-1",
    name: "Crispy Chicken Wings",
    description: "6 pieces of golden crispy chicken wings with dipping sauce",
    price: 1800,
    image: "/crispy-chicken-wings.jpg",
    category: "Chicken",
  },
  {
    id: "chicken-2",
    name: "Chicken Tenders",
    description: "5 pieces of tender chicken strips with fries",
    price: 2000,
    image: "/chicken-tenders-with-fries.jpg",
    category: "Chicken",
  },
  {
    id: "chicken-3",
    name: "Grilled Chicken Platter",
    description: "Half grilled chicken with sides and sauce",
    price: 3000,
    image: "/grilled-chicken-platter.jpg",
    category: "Chicken",
  },
  {
    id: "chicken-4",
    name: "Spicy Chicken Bucket",
    description: "8 pieces of spicy fried chicken",
    price: 4500,
    image: "/bucket-of-fried-chicken.jpg",
    category: "Chicken",
  },

  // Desserts
  {
    id: "dessert-1",
    name: "Chocolate Brownie",
    description: "Warm chocolate brownie with vanilla ice cream",
    price: 1200,
    image: "/chocolate-brownie-ice-cream.png",
    category: "Desserts",
  },
  {
    id: "dessert-2",
    name: "Apple Pie",
    description: "Classic apple pie with cinnamon",
    price: 1000,
    image: "/apple-pie-slice.png",
    category: "Desserts",
  },
  {
    id: "dessert-3",
    name: "Ice Cream Sundae",
    description: "Three scoops with toppings and syrup",
    price: 1500,
    image: "/ice-cream-sundae.png",
    category: "Desserts",
  },

  // Drinks
  {
    id: "drink-1",
    name: "Fresh Orange Juice",
    description: "Freshly squeezed orange juice",
    price: 800,
    image: "/fresh-orange-juice-glass.jpg",
    category: "Drinks",
  },
  {
    id: "drink-2",
    name: "Soft Drink",
    description: "Choice of Coke, Sprite, or Fanta",
    price: 500,
    image: "/soft-drink-can.jpg",
    category: "Drinks",
  },
  {
    id: "drink-3",
    name: "Smoothie",
    description: "Mixed fruit smoothie",
    price: 1200,
    image: "/fruit-smoothie.png",
    category: "Drinks",
  },
  {
    id: "drink-4",
    name: "Milkshake",
    description: "Chocolate, vanilla, or strawberry",
    price: 1500,
    image: "/milkshake-glass.jpg",
    category: "Drinks",
  },
]
